_target_: msr.data.dataset_providers.MimicDatasetProvider
representation_types:
  - whole_signal_waveforms
  # - windows_waveforms
  # - beats_waveforms
  - agg_beat_waveforms
  # - whole_signal_features
  # - windows_features
  # - beats_features
  # - agg_beat_features
windows_params:
  win_len_s: 20
  step_s: 18
beats_params:
  source_channel: ecg
  align_peaks_loc: True
agg_beat_params:
  valid_only: False
n_beats: 100
target: sbp_dbp_avg
