repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=15000']

  - repo: local
    hooks:
      - id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        entry: black
        language: python
        require_serial: true
        types_or: [python, pyi]
        args: # arguments to configure black
          - --line-length=120


      - id: blacken-docs
        name: blacken-docs
        description: Run `black` on python code blocks in documentation files
        entry: blacken-docs
        language: python
        language_version: python3
        files: '\.(rst|md|markdown|py|tex)$'

      - id: isort
        name: isort
        entry: isort
        require_serial: true
        language: python
        language_version: python3
        types_or: [cython, pyi, python]
        args: ["--profile", "black", "--filter-files"]


      # - id: black-jupyter
      #   name: black-jupyter
      #   description:
      #     "Black: The uncompromising Python code formatter (with Jupyter Notebook support)"
      #   entry: black
      #   language: python
      #   minimum_pre_commit_version: 2.9.2
      #   require_serial: true
      #   types_or: [python, pyi, jupyter]
      #   additional_dependencies: [".[jupyter]"]


      # - id: pylint
      #   name: pylint
      #   entry: pylint
      #   language: python
      #   types: [python]
      #   require_serial: true

      # - id: mypy
      #   name: mypy
      #   entry: mypy
      #   language: python
      #   types_or: [python, pyi]
      #   args: ["--ignore-missing-imports", "--scripts-are-modules"]
      #   require_serial: true
      #   additional_dependencies: []

      # - id: pydocstyle
      #   name: pydocstyle
      #   description: pydocstyle is a static analysis tool for checking compliance with Python docstring conventions.
      #   entry: pydocstyle
      #   language: python
      #   types: [python]
