_target_: msr.training.data.datamodules.MimicDataModule
representation_type: whole_signal_features
target: sbp_dbp_avg
batch_size: 64
num_workers: 8
train_transform:
  _target_: msr.training.data.transforms.Flatten
  start_dim: 0
  end_dim: -1

inference_transform:
  _target_: msr.training.data.transforms.Flatten
  start_dim: 0
  end_dim: -1
