_target_: msr.training.data.datamodules.PtbXLDataModule
representation_type: ${representation_type}
fs: 100
target: diagnostic_class
batch_size: 64
num_workers: 8
train_transform: ${transforms.train_transform}
inference_transform: ${transforms.inference_transform}
# train_transform:
#   _target_: msr.training.data.transforms.Flatten
#   start_dim: 0
#   end_dim: -1

# inference_transform:
#   _target_: msr.training.data.transforms.Flatten
#   start_dim: 0
#   end_dim: -1
