defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

raw_data:
  fs: 125

download: false
create_splits: true
max_samples_per_subject: 50     # maximum number of samples per subject in created dataset
sig_names:                      # which signals to obtain from mimic
  - ABP                         # Arterial Blood Pressure
  - PLETH                       # PPG
  - II                          # Lead II ECG
sample_len_sec: 240             # desired length of sample in seconds
max_n_same: 10                  # maximum number of repeated samples treated as valid
split:
  train_size: 0.7
  val_size: 0.15
  test_size: 0.15
  random_state: 42
  max_samples_per_subject_for_split: 8
  sample_len_sec: 60
  targets:
    - sbp_dbp_avg
