_target_: msr.training.trainers.DLClassifierTrainer
_partial_: true
trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: auto
  devices: 1
  max_epochs: 5
  deterministic: warn # true
# model
# datamodule
