_target_: msr.training.trainers.DLRegressorTrainer
_partial_: true
trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: auto
  devices: 1
  max_epochs: 50
  deterministic: true
# model
# datamodule
