downsaple:
  train_transform:
    _target_: msr.training.data.transforms.Downsample
    dim: 0
    ratio: 2

  inference_transform:
    _target_: msr.training.data.transforms.Downsample
    dim: 0
    ratio: 2
