train_transform:
  _target_: torchvision.transforms.Compose
  transforms:
  - _target_: msr.training.data.transforms.Downsample
    dim: 0
    n: 2
  - _target_: msr.training.data.transforms.Permute
    dims: [1, 0]


inference_transform:
  _target_: torchvision.transforms.Compose
  transforms:
  - _target_: msr.training.data.transforms.Downsample
    dim: 0
    n: 2
  - _target_: msr.training.data.transforms.Permute
    dims: [1, 0]
