train_transform:
  _target_: torchvision.transforms.Compose
  transforms:
  - _target_: msr.training.data.transforms.Flatten
    start_dim: 0
    end_dim: -1
  - _target_: msr.training.data.transforms.Downsample
    dim: 0
    n: 2


inference_transform:
  _target_: torchvision.transforms.Compose
  transforms:
  - _target_: msr.training.data.transforms.Flatten
    start_dim: 0
    end_dim: -1
  - _target_: msr.training.data.transforms.Downsample
    dim: 0
    n: 2
