flatten:
  train_transform:
    _target_: msr.training.data.transforms.Flatten
    start_dim: 0
    end_dim: -1

  inference_transform:
    _target_: msr.training.data.transforms.Flatten
    start_dim: 0
    end_dim: -1
