defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

raw_data:
  fs: 125

beats_params:
  source_channel: ecg
n_beats: 120
agg_beat_params:
  valid_only: false
windows_params:
  win_len_s: 20
  step_s: 18
n_jobs: 1
representation_types:
  # - whole_signal_waveforms
  # - windows_waveforms
  # - beats_waveforms
  # - agg_beat_waveforms
  - whole_signal_features
  - windows_features
  - beats_features
  - agg_beat_features
