_target_: msr.models.modules.ClassifierModule
net:
  _target_: msr.models.architectures.networks.cnn.CNNClassifier
  _partial_: true
  # num_classes
  # in_channels
  dim: 1
  out_channels: [16, 32, 64, 128]
  maxpool_kernel_size: [2, 1, 2, 1]
  kernel_size: [7, 5, 5, 3]
  stride: 1
  padding: same
  dilation: 1
  transpose: false
  use_batchnorm: true
  activation: ReLU
  use_residual: True
  hidden_dims: [128, 128]
