_target_: msr.models.modules.RegressorModule
learning_rate: 0.01
weight_decay: 0.001
net:
  _target_: msr.models.architectures.networks.cnn.CNNRegressor
  _partial_: true
  # num_classes
  # in_channels
  conv0_kernel_size: 7
  conv0_channels: 128
  layers: [1, 1, 1]
  ff_hidden_dims: [128, 128]
  ff_dropout: 0.2
