_target_: sklearn.tree.DecisionTreeClassifier
splitter: best
criterion: gini
max_depth: null
min_samples_split: 2
min_samples_leaf: 1
min_weight_fraction_leaf: 0
max_features: sqrt
max_leaf_nodes: null
min_impurity_decrease: 0
random_state: ${seed}
