_target_: sklearn.tree.DecisionTreeRegressor
splitter: best
criterion: squared_error
max_depth: null
min_samples_split: 2
min_samples_leaf: 1
min_weight_fraction_leaf: 0
max_features: 1.0
max_leaf_nodes: null
min_impurity_decrease: 0
class_weight: balanced
random_state: ${seed}
