_target_: lightgbm.LGBMClassifier
boosting_type: dart
num_leaves: 31
max_depth: -1
learning_rate: 0.1
n_estimators: 600
subsample_for_bin: 200000
objective: null
class_weight: balanced
min_split_gain: 0
min_child_weight: 0.001
min_child_samples: 20
subsample: 1.0
subsample_freq: 0
colsample_bytree: 1.0
reg_alpha: 0.0
reg_lambda: 0.0
random_state: ${seed}
n_jobs: -1
importance_type: split
