_target_: msr.models.modules.RegressorModule
learning_rate: 0.01
weight_decay: 0.001
net:
  _target_: msr.models.architectures.networks.mlp.MLPRegressor
  _partial_: true
  # num_classes
  # input_size
  hidden_dims: [256, 512, 256]
  weight_norm: False
  batch_norm: True
  dropout: 0.2
  activation: ReLU
