# https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html
_target_: sklearn.ensemble.RandomForestRegressor
n_estimators: 500
criterion: squared_error
max_depth: null
min_samples_split: 2
min_samples_leaf: 1
min_weight_fraction_leaf: 0
max_features: sqrt
max_leaf_nodes: null
min_impurity_decrease: 0
bootstrap: true
n_jobs: -1
random_state: ${seed}
